### ISSUE TITLE
Issues with links in sections 5. & 6.

### ISSUE THREAD

**Issue by Theo6890** [Quillhash/QuillAudit_Auditor_Roadmap#3]
- (5.) Secureum Security Pitfalls 101 & (6.) Secureum Security Pitfalls 101: same link
- (5.) Secureum Security Pitfalls 201 & (6.) Security Security Pitfalls 201: same link

**Comment by Sm4rty-1** [comment]
Thanks for bringing this to our attention.

**Comment by Theo6890** [comment]
Your welcome 😊
