### ISSUE TITLE
docs: mastering ethereum book - mandatory chapter

### ISSUE THREAD

**Issue by Theo6890** [Quillhash/QuillAudit_Auditor_Roadmap#4]
I have read the whole Ethereum book and according to me the most important pages are:

- 1
- 4
- 5
- 6
- 7
- 9
- 13
- 14

Why replace 2 & 3 by 7 & 9? 

**Firstly**, 2 & 3 are generalities that can be found anywhere, even in some EVM toolkit (like HardHat).

**Secondly**, there are specific points that can be ask in entry tests as a Solidity Developer or in challenges like Secureum and quite tricky to find.

That being said I think this proposal about mandatory chapters make more sense.

**Comment by Sm4rty-1** [comment]
Thanks for your Suggestion. Will update it soon.

**Comment by Theo6890** [comment]
The chapters have been replaced in the `README.md` but in in `xmind`
